[package]
name = "addr-osmify"
version = "0.1.0"
authors = ["Miklos Vajna <vmiklos@vmiklos.hu>"]
edition = "2021"

[dependencies]
anyhow = "1.0.100"
isahc = "1.7.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
url = "2.5.7"
